export const answers = [
    "Yes.",
    "It is certain.",
    "It is decidedly so.",
    "Without a doubt.",
    "Yes definitely.",
    "Most likely.",
    "Signs point to yes.",
    "Big pp energy comes from this.",
    "Hot dog!",
    "yEEEEEESS!",
    "No",
    "Don't count on it",
    "My pp sources say no.",
    "Hmm i don't know.",
    "nOOOOOOOO!",
    "You need more pp power.",
    "pp energy not enough.",
    "Try againn.",
    "I'm Pomu.",
    "Pomu sleepy...",
    "NUT",
];
